import turtle
tr = turtle.Turtle()
tr.pensize(5)
tr.color("blue")
tr.penup()
tr.goto(-110, -25)
tr.pendown()
tr.circle(45)
tr.color("black")
tr.penup()
tr.goto(0, -25)
tr.pendown()
tr.circle(45)
tr.color("red")
tr.penup()
tr.goto(110, -25)
tr.pendown()
tr.circle(45)
tr.color("yellow")
tr.goto(-55, -75)
tr.pendown()
tr.circle(45)
tr.color("green")
tr.pendown()
tr.circle(45)
tr.goto(55, -75)
tr.pendown()


#define a dynamic function that takes on colors that can draw an olympic logo